import { useState, useContext } from "react";
import { useNavigate } from "react-router-dom";
import { AppContext } from "../context/AppContext";
import { ClipboardList, Send, AlertCircle } from "lucide-react";

export default function LaboratoryBookingForm() {
  const navigate = useNavigate();
  const {
    laboratories,
    selectedLaboratory,
    setSelectedLaboratory,
    mySchedules,
    setMySchedules,
  } = useContext(AppContext);

  // Form state
  const [formData, setFormData] = useState({
    namalab: selectedLaboratory ? String(selectedLaboratory.id) : "",
    hari: "",
    jam: "",
    dosen: "",
    prodi: "",
    kelas: "",
    matkul: "",
    tanggalInput: new Date().toISOString().split("T")[0], // default to today
    mahasiswa: "",
    nim: "",
    numberwa: "",
    jumlahHadir: "",
  });

  const [selectedScheduleId, setSelectedScheduleId] = useState("");
  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Uncompleted schedules list (schedule generated by admin without student details)
  const uncompletedSchedules = mySchedules.filter(
    (s) => s.mahasiswa === "Admin (Penjadwalan)" || s.mahasiswa === "-" || !s.mahasiswa
  );

  const listHari = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"];
  const listProdi = ["Teknik Informatika", "Sistem Informasi", "Matematika", "Sains Data", "Fisika", "Biologi"];

  const getSelectedLabName = () => {
    const labId = parseInt(formData.namalab, 10);
    const lab = laboratories.find((l) => l.id === labId);
    return lab ? lab.name : "Laboratorium";
  };

  const handleScheduleSelect = (scheduleId) => {
    setSelectedScheduleId(scheduleId);
    setErrors({});
    if (!scheduleId) {
      setFormData({
        namalab: selectedLaboratory ? String(selectedLaboratory.id) : "",
        hari: "",
        jam: "",
        dosen: "",
        prodi: "",
        kelas: "",
        matkul: "",
        tanggalInput: new Date().toISOString().split("T")[0],
        mahasiswa: "",
        nim: "",
        numberwa: "",
        jumlahHadir: "",
      });
      return;
    }

    const schedule = mySchedules.find((s) => s.id === parseInt(scheduleId, 10));
    if (schedule) {
      const lab = laboratories.find((l) => l.name === schedule.ruang);
      setFormData({
        namalab: lab ? String(lab.id) : "",
        hari: schedule.hari || "",
        jam: schedule.jam || "",
        dosen: schedule.dosen || "",
        prodi: schedule.prodi || "",
        kelas: schedule.kelas || "-",
        matkul: schedule.matkul || "",
        tanggalInput: schedule.tanggalInput || "",
        mahasiswa: "",
        nim: "",
        numberwa: "",
        jumlahHadir: "",
      });
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));

    if (errors[name]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[name];
        return next;
      });
    }
  };

  const validate = () => {
    const newErrors = {};

    if (!formData.namalab) {
      newErrors.namalab = "Silakan pilih laboratorium.";
    }
    if (!formData.hari) {
      newErrors.hari = "Silakan pilih hari.";
    }
    if (!formData.jam) {
      newErrors.jam = "Silakan masukkan jam penggunaan.";
    }
    if (!formData.dosen.trim()) {
      newErrors.dosen = "Nama dosen pengampu wajib diisi.";
    }
    if (!formData.prodi) {
      newErrors.prodi = "Silakan pilih program studi.";
    }
    if (!formData.kelas.trim()) {
      newErrors.kelas = "Kelas wajib diisi.";
    }
    if (!formData.matkul.trim()) {
      newErrors.matkul = "Mata kuliah wajib diisi.";
    }
    if (!formData.tanggalInput) {
      newErrors.tanggalInput = "Silakan masukkan tanggal penggunaan.";
    }
    if (!formData.mahasiswa.trim()) {
      newErrors.mahasiswa = "Nama mahasiswa wajib diisi.";
    }
    if (!formData.nim.trim()) {
      newErrors.nim = "NIM mahasiswa wajib diisi.";
    }
    if (!formData.numberwa.trim()) {
      newErrors.numberwa = "Nomor telepon wajib diisi.";
    } else if (!/^(\+?62|08)\d{8,13}$/.test(formData.numberwa.trim())) {
      newErrors.numberwa = "Format nomor WhatsApp tidak valid. Contoh: 081234567890";
    }
    if (!formData.jumlahHadir) {
      newErrors.jumlahHadir = "Jumlah yang hadir wajib diisi.";
    } else if (parseInt(formData.jumlahHadir, 10) < 1) {
      newErrors.jumlahHadir = "Jumlah hadir minimal 1 orang.";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!validate()) return;

    setIsSubmitting(true);

    setTimeout(() => {
      if (selectedScheduleId) {
        // Update existing schedule (connect student details to the admin-created schedule)
        setMySchedules(
          mySchedules.map((s) =>
            s.id === parseInt(selectedScheduleId, 10)
              ? {
                  ...s,
                  mahasiswa: formData.mahasiswa.trim(),
                  nim: formData.nim.trim(),
                  numberwa: formData.numberwa.trim(),
                  jumlahHadir: parseInt(formData.jumlahHadir, 10),
                }
              : s
          )
        );
      } else {
        // Create new manual schedule
        const newSchedule = {
          id: Date.now(),
          hari: formData.hari,
          jam: formData.jam,
          dosen: formData.dosen.trim(),
          prodi: formData.prodi,
          kelas: formData.kelas.trim(),
          matkul: formData.matkul.trim(),
          ruang: getSelectedLabName(),
          tanggalInput: formData.tanggalInput,
          mahasiswa: formData.mahasiswa.trim(),
          nim: formData.nim.trim(),
          numberwa: formData.numberwa.trim(),
          jumlahHadir: parseInt(formData.jumlahHadir, 10),
        };
        setMySchedules([newSchedule, ...mySchedules]);
      }

      setSelectedLaboratory(null);
      setIsSubmitting(false);

      alert(`Log book penggunaan ${getSelectedLabName()} berhasil disimpan!`);
      navigate("/");
    }, 600);
  };

  return (
    <div className="px-6 py-4 max-w-3xl mx-auto">
      <div className="bg-white rounded-2xl shadow-lg border border-slate-100 overflow-hidden transition-all hover:shadow-xl">
        {/* Header */}
        <div className="p-6 text-white flex items-center gap-4" style={{ backgroundColor: "#4b8fca" }}>
          <div className="p-3 bg-white/10 rounded-xl">
            <ClipboardList size={26} />
          </div>
          <div>
            <h1 className="text-xl font-bold font-display">Log Book Penggunaan Laboratorium</h1>
            <p className="text-xs text-white/80 mt-0.5">Isi form di bawah ini untuk mencatat penggunaan ruang laboratorium.</p>
          </div>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="p-6 space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {/* Jadwal Kuliah Selection */}
            <div className="md:col-span-2 bg-blue-50/40 p-4.5 rounded-2xl border border-blue-100/50">
              <label className="block text-xs font-bold text-blue-700 uppercase tracking-wider mb-2">
                Pilih Jadwal Kuliah yang Tersedia (Opsional)
              </label>
              <p className="text-[10px] text-slate-500 mb-3">
                Pilih jadwal kuliah dari Admin untuk mengisi data perkuliahan secara otomatis. Lewati jika ingin input manual.
              </p>
              <select
                value={selectedScheduleId}
                onChange={(e) => handleScheduleSelect(e.target.value)}
                className="w-full p-3 border border-blue-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm bg-white cursor-pointer transition font-semibold text-slate-700"
              >
                <option value="">-- Input Manual / Pemesanan Mandiri --</option>
                {uncompletedSchedules.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.ruang} | {s.hari}, {s.jam} - {s.matkul} ({s.dosen})
                  </option>
                ))}
              </select>
            </div>

            {/* Notification Banner when schedule is selected */}
            {selectedScheduleId && (
              <div className="md:col-span-2 bg-emerald-50 p-4 rounded-xl border border-emerald-100 flex items-start gap-2.5">
                <span className="text-emerald-500 text-sm">✓</span>
                <p className="text-[11px] text-emerald-800 leading-normal">
                  <strong>Jadwal Kuliah Terhubung:</strong> Informasi perkuliahan di bawah ini telah diisi otomatis dan dikunci. Silakan langsung isi bagian <strong>Data Penanggung Jawab Mahasiswa</strong> di bawah.
                </p>
              </div>
            )}

            {/* Lab Selection */}
            <div className="md:col-span-2">
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Pilih Laboratorium <span className="text-red-500">*</span>
              </label>
              <select
                name="namalab"
                value={formData.namalab}
                onChange={handleChange}
                disabled={!!selectedScheduleId}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm cursor-pointer transition ${
                  errors.namalab ? "border-red-300 bg-red-50/30" : "border-slate-200"
                } ${selectedScheduleId ? "bg-slate-100 text-slate-400 cursor-not-allowed" : "bg-slate-50/50"}`}
              >
                <option value="">-- Pilih Laboratorium --</option>
                {laboratories.map((lab) => (
                  <option key={lab.id} value={lab.id}>
                    {lab.name}
                  </option>
                ))}
              </select>
              {errors.namalab && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.namalab}
                </p>
              )}
            </div>

            {/* Hari */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Hari <span className="text-red-500">*</span>
              </label>
              <select
                name="hari"
                value={formData.hari}
                onChange={handleChange}
                disabled={!!selectedScheduleId}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm cursor-pointer transition ${
                  errors.hari ? "border-red-300 bg-red-50/30" : "border-slate-200"
                } ${selectedScheduleId ? "bg-slate-100 text-slate-400 cursor-not-allowed" : "bg-slate-50/50"}`}
              >
                <option value="">-- Pilih Hari --</option>
                {listHari.map((day) => (
                  <option key={day} value={day}>{day}</option>
                ))}
              </select>
              {errors.hari && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.hari}
                </p>
              )}
            </div>

            {/* Jam */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Jam Penggunaan <span className="text-red-500">*</span>
              </label>
              <input
                type={selectedScheduleId ? "text" : "time"}
                name="jam"
                value={formData.jam}
                onChange={handleChange}
                disabled={!!selectedScheduleId}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm transition ${
                  errors.jam ? "border-red-300 bg-red-50/30" : "border-slate-200"
                } ${selectedScheduleId ? "bg-slate-100 text-slate-400 cursor-not-allowed" : "bg-slate-50/50"}`}
              />
              {errors.jam && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.jam}
                </p>
              )}
            </div>

            {/* Tanggal Input */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Tanggal Penggunaan <span className="text-red-500">*</span>
              </label>
              <input
                type={selectedScheduleId ? "text" : "date"}
                name="tanggalInput"
                value={formData.tanggalInput}
                onChange={handleChange}
                disabled={!!selectedScheduleId}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm transition ${
                  errors.tanggalInput ? "border-red-300 bg-red-50/30" : "border-slate-200"
                } ${selectedScheduleId ? "bg-slate-100 text-slate-400 cursor-not-allowed" : "bg-slate-50/50"}`}
              />
              {errors.tanggalInput && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.tanggalInput}
                </p>
              )}
            </div>

            {/* Nama Dosen */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Nama Dosen <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                name="dosen"
                placeholder="Contoh: Dr. Budi"
                value={formData.dosen}
                onChange={handleChange}
                disabled={!!selectedScheduleId}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm transition ${
                  errors.dosen ? "border-red-300 bg-red-50/30" : "border-slate-200"
                } ${selectedScheduleId ? "bg-slate-100 text-slate-400 cursor-not-allowed" : "bg-slate-50/50"}`}
              />
              {errors.dosen && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.dosen}
                </p>
              )}
            </div>

            {/* Prodi */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Program Studi (Prodi) <span className="text-red-500">*</span>
              </label>
              {selectedScheduleId ? (
                <input
                  type="text"
                  name="prodi"
                  value={formData.prodi}
                  disabled
                  className="w-full p-3 border border-slate-200 rounded-xl text-sm bg-slate-100 text-slate-400 cursor-not-allowed"
                />
              ) : (
                <select
                  name="prodi"
                  value={formData.prodi}
                  onChange={handleChange}
                  className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm bg-slate-50/50 cursor-pointer transition ${
                    errors.prodi ? "border-red-300 bg-red-50/30" : "border-slate-200"
                  }`}
                >
                  <option value="">-- Pilih Program Studi --</option>
                  {listProdi.map((p) => (
                    <option key={p} value={p}>{p}</option>
                  ))}
                </select>
              )}
              {errors.prodi && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.prodi}
                </p>
              )}
            </div>

            {/* Kelas */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Kelas <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                name="kelas"
                placeholder="Contoh: TI-4A"
                value={formData.kelas}
                onChange={handleChange}
                disabled={!!selectedScheduleId}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm transition ${
                  errors.kelas ? "border-red-300 bg-red-50/30" : "border-slate-200"
                } ${selectedScheduleId ? "bg-slate-100 text-slate-400 cursor-not-allowed" : "bg-slate-50/50"}`}
              />
              {errors.kelas && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.kelas}
                </p>
              )}
            </div>

            {/* Mata Kuliah */}
            <div className="md:col-span-2">
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Mata Kuliah <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                name="matkul"
                placeholder="Contoh: Pemrograman Web"
                value={formData.matkul}
                onChange={handleChange}
                disabled={!!selectedScheduleId}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm transition ${
                  errors.matkul ? "border-red-300 bg-red-50/30" : "border-slate-200"
                } ${selectedScheduleId ? "bg-slate-100 text-slate-400 cursor-not-allowed" : "bg-slate-50/50"}`}
              />
              {errors.matkul && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.matkul}
                </p>
              )}
            </div>

            {/* ====== BAGIAN DATA MAHASISWA ====== */}
            <div className="md:col-span-2 border-t border-slate-100 pt-4 mt-2">
              <h3 className="text-sm font-bold text-slate-800 font-display mb-3">Data Penanggung Jawab Mahasiswa</h3>
            </div>

            {/* Nama Mahasiswa */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Nama Mahasiswa <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                name="mahasiswa"
                placeholder="Nama Lengkap Penanggung Jawab"
                value={formData.mahasiswa}
                onChange={handleChange}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm bg-slate-50/50 transition ${
                  errors.mahasiswa ? "border-red-300 bg-red-50/30" : "border-slate-200"
                }`}
              />
              {errors.mahasiswa && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.mahasiswa}
                </p>
              )}
            </div>

            {/* NIM */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                NIM <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                name="nim"
                placeholder="Nomor Induk Mahasiswa"
                value={formData.nim}
                onChange={handleChange}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm bg-slate-50/50 transition ${
                  errors.nim ? "border-red-300 bg-red-50/30" : "border-slate-200"
                }`}
              />
              {errors.nim && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.nim}
                </p>
              )}
            </div>

            {/* Nomor WA */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Nomor Telepon <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                name="numberwa"
                placeholder="Contoh: 081234567890"
                value={formData.numberwa}
                onChange={handleChange}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm bg-slate-50/50 transition ${
                  errors.numberwa ? "border-red-300 bg-red-50/30" : "border-slate-200"
                }`}
              />
              {errors.numberwa && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.numberwa}
                </p>
              )}
            </div>

            {/* Jumlah yang Hadir */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                Jumlah Hadir <span className="text-red-500">*</span>
              </label>
              <input
                type="number"
                name="jumlahHadir"
                placeholder="Estimasi mahasiswa hadir"
                min="1"
                value={formData.jumlahHadir}
                onChange={handleChange}
                className={`w-full p-3 border rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm bg-slate-50/50 transition ${
                  errors.jumlahHadir ? "border-red-300 bg-red-50/30" : "border-slate-200"
                }`}
              />
              {errors.jumlahHadir && (
                <p className="text-red-500 text-xs font-semibold mt-1 flex items-center gap-1">
                  <AlertCircle size={12} /> {errors.jumlahHadir}
                </p>
              )}
            </div>
          </div>

          {/* Submit */}
          <div className="flex justify-end pt-3">
            <button
              type="submit"
              disabled={isSubmitting}
              className="flex items-center gap-2 px-6 py-3 text-white rounded-xl font-bold text-sm shadow-md transition hover:scale-[1.02] active:scale-[0.98] cursor-pointer disabled:opacity-50"
              style={{ backgroundColor: "#4bc9bf", boxShadow: "0 4px 14px rgba(75, 201, 191, 0.3)" }}
            >
              <Send size={15} />
              {isSubmitting ? "Menyimpan..." : "Simpan Log Book"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
